### PR TITLE
CMake: find python if dependencies were built without it, fix #69

### LINKED ISSUE #69: Robotpkg error
Hi,

I get the following error when building the package with robotpkg:
```
CMake Error at src/CMakeLists.txt:23 (python_install_on_site):
Unknown CMake command "python_install_on_site".
Call Stack (most recent call first):
src/CMakeLists.txt:28 (install_python_files)


-- Configuring incomplete, errors occurred!
```

I'm a little surprised since this has not changed and it seems the CMake submodule has no changes related to this. Anyone understands the issue ?

EDIT: I still don't understand why it passed on robotpkg build farm: http://robotpkg.openrobots.org/rbulk/robotpkg/graphics/py-qt-hpp-gepetto-viewer/index.html#py38-qt5-hpp-gepetto-viewer-4.15.1

### PR DESCRIPTION
**Pull request by nim65s**

### CODE REVIEW

**Comment by nim65s** [comment]
@jmirabel : do you need this to be added as a patch on robotpkg ?

**Comment by jmirabel** [comment]
> @jmirabel : do you need this to be added as a patch on robotpkg ?

Yes, please.

**Review by jmirabel — APPROVED** [review]
Thanks.

**Comment by nim65s** [comment]
You can already grab it there: https://github.com/nim65s/robotpkg/commit/e11e3ca7aad1314bceb93070950f405ce90b8723 ; it is probably going to get merged in the main repo soon.

**Comment by nim65s** [comment]
Oops, I messed the submoduled

**Comment by nim65s** [comment]
https://github.com/nim65s/robotpkg/commit/521277c919beab3376053af713fdf41b699db271

**Pull request merged**
