### PR TITLE
Remove light source when loading collada meshes.

### PR DESCRIPTION
**Pull request by florent-lamiraux**
This PR is not meant to be merged now since it does not solve the problem of collada mesh that illuminate the scene.  
@jmirabel: can you have a quick look and let me know whether this fits what we agreed about ?

### CODE REVIEW

**Comment by jmirabel** [comment]
Yes, this should work.

**Comment by florent-lamiraux** [comment]
Now it works. The child nodes of URDF nodes are iterated recursively and method removeLightSources is called when applicable.

**Comment by jmirabel** [comment]
Do you get visually a result which is satisfactory ?

**Comment by florent-lamiraux** [comment]
yes.

**Comment by jmirabel** [comment]
Thanks.

**Pull request merged**
